import raw from '../data/content.json'
import type { SiteContent } from '../types'

// content.json is generated by scripts/fetch-content.mjs (predev/prebuild)
export const content = raw as unknown as SiteContent
